//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookList
    {
        public int bId { get; set; }
        public string bTitle { get; set; }
        public string bOriginal { get; set; }
        public string bAuthor { get; set; }
        public int bYear { get; set; }
        public string bPubHouse { get; set; }
        public long bISBN { get; set; }
        public string bTrans { get; set; }
        public decimal bMoney { get; set; }
        public string bLaun { get; set; }
        public string bIntroduce { get; set; }
        public string bURL { get; set; }
    }
}
